sudo: false
language: java
jdk:
  - openjdk11
  - openjdk-ea
  - oraclejdk11
  - oraclejdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea
    - jdk: oraclejdk-ea

before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
  - tar xzvf apache-maven-3.8.1-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.8.1/bin:$PATH
  - mvn -v
